# Generated by Django 4.1.7 on 2024-02-22 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('video', models.FileField(upload_to='video', verbose_name='Видео')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Создано')),
            ],
        ),
    ]
